version: '3.5'
services:

  leproxy:
    build: leproxy
    container_name: ${APP_NAME}_leproxy
    restart: always
    environment:
      - USERNAME=${PROXY_USERNAME}
      - PASSWORD=${PROXY_PASSWORD}
      - PORT=${PROXY_PORT}
    networks:
      backend:
        aliases:
          - ${APP_NAME}_leproxy

  kcptun:
    build: kcptun
    container_name: ${APP_NAME}_kcptun
    restart: always
    depends_on:
      - leproxy
    ports:
      - ${KCPTUN_PORT}:8082/udp

    networks:
      backend:
        aliases:
          - ${APP_NAME}_kcptun

networks:
  backend:
    name: ${APP_NAME}_network